program: C:\Users\zcemg08\Documents\GitHub\Mol_gan\ML_TEST\train_no_reward.py
method:  grid
project: dcgan
description : GAN molecular no reward
parameters:
  seed:
    value: 42
  Lambda:
    value: 0
  clip_value:
    value: 0
  z_dim:
    value: 64
  drop_out:
    value: 0.1
  bz:
    value: 64
  epochs:
    value: 10
  loss:
    value: 'wgan'
  h1_d:
    value: 128
  h2_d:
    value: 64
  h3_d:
    value: 128
  h4_d:
    value: 64
  nonlinearity_D:
    value: 'relu'
  Spectral_Norm_D:
    value: True
  batch_norm_D:
    value: false
  weight_init_D:
    value: 'kaiming_normal'
  weight_init_last_D:
    value: 'kaiming_normal'
  n_critic:
    value: 5
  h1_g:
    value: 128
  h2_g:
    value: 256
  h3_g:
    value: 512
  batch_norm_G:
    value: false
  nonlinearity_G:
    value: 'tanh'
  weight_init_G:
    value: 'xavier_normal'
  weight_init_last_G:
    value: 'xavier_normal'
  temp:
    value: 0.1
  optimizer:
    value: 'RMS'
  grad_correction:
    value: false
  lr_d:
    values: [0.001, 0.0001]
  lr_g:
    values: [0.001, 0.0001]
