program: C:\Users\zcemg08\Documents\GitHub\Mol_gan\ML_TEST\train_no_reward.py
method:  grid
project: molecular_gan
description : GAN molecular no reward
parameters:
  seed:
    value: 42
  h1_d:
    value: 128
  h2_d:
    value: 64
  h3_d:
    value: 128
  h4_d:
    value: 64
  h1_g:
    value: 128
  h2_g:
    value: 256
  h3_g:
    value: 512
  batch_norm_G:
    value: false
  batch_norm_D:
    value: true
  nonlinearity_G:
    value: 'Tanh'
  nonlinearity_D:
    value: 'LeakyRelu'
  drop_out:
    value: 0.1
  temp:
    value: 0.1
  z_dim:
    value: 32
  LAMBDA:
    value: 10.0
  n_critic:
    value: 5
  bz:
    value: 64
  epochs:
    value: 5
  eps:
    value: 0.0001
  optimizer:
    value: 'adam'
  lr_d:
    values: [0.0001, 0.001]
  lr_g:
    values: [0.0001, 0.001]
