name: MolGAN
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.9.0
  - astor==0.7.1
  - attrs==19.3.0
  - backcall==0.1.0
  - blas==1.0
  - bleach==1.5.0
  - brotlipy==0.7.0
  - bzip2==1.0.8
  - c-ares==1.15.0
  - ca-certificates==2020.4.5.1
  - cairo==1.14.12
  - certifi==2020.4.5.1
  - cffi==1.11.5
  - chardet==3.0.4
  - cryptography==2.9.2
  - decorator==4.4.2
  - defusedxml==0.6.0
  - entrypoints==0.3
  - fontconfig==2.13.0
  - freetype==2.9.1
  - gast==0.3.3
  - gettext==0.19.8.1
  - glib==2.63.1
  - grpcio==1.23.0
  - html5lib==0.9999999
  - icu==58.2
  - idna==2.9
  - importlib-metadata==1.6.0
  - importlib_metadata==1.6.0
  - intel-openmp==2019.4
  - ipykernel==5.3.0
  - ipython==7.14.0
  - ipython_genutils==0.2.0
  - jedi==0.17.0
  - jinja2==2.11.2
  - joblib==0.15.1
  - jpeg==9b
  - json5==0.9.0
  - jsonschema==3.2.0
  - jupyter_client==6.1.3
  - jupyter_core==4.6.3
  - jupyterlab==2.1.2
  - jupyterlab_server==1.1.4
  - libboost==1.67.0
  - libcxx==10.0.0
  - libedit==3.1.20181209
  - libffi==3.2.1
  - libiconv==1.16
  - libpng==1.6.37
  - libprotobuf==3.11.4
  - libsodium==1.0.17
  - libtiff==4.1.0
  - libxml2==2.9.9
  - llvm-openmp==10.0.0
  - markdown==3.2.2
  - markupsafe==1.1.1
  - mistune==0.8.4
  - mkl==2019.4
  - mkl-service==2.3.0
  - mkl_fft==1.0.15
  - mkl_random==1.1.0
  - nbconvert==5.6.1
  - nbformat==5.0.6
  - ncurses==6.2
  - notebook==6.0.3
  - numpy==1.18.1
  - numpy-base==1.18.1
  - openssl==1.1.1g
  - pandas==1.0.3
  - pandoc==2.9.2.1
  - pandocfilters==1.4.2
  - parso==0.7.0
  - pcre==8.43
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow==7.1.2
  - pip==20.0.2
  - pixman==0.38.0
  - prometheus_client==0.7.1
  - prompt-toolkit==3.0.5
  - protobuf==3.11.4
  - ptyprocess==0.6.0
  - py-boost==1.67.0
  - pycparser==2.20
  - pygments==2.6.1
  - pyopenssl==19.1.0
  - pyrsistent==0.16.0
  - pysocks==1.7.1
  - python==3.6.10
  - python-dateutil==2.8.1
  - python_abi==3.6
  - pytz==2020.1
  - pyzmq==19.0.1
  - rdkit==2020.03.2.0
  - readline==8.0
  - requests==2.23.0
  - scikit-learn==0.22.1
  - scipy==1.4.1
  - send2trash==1.5.0
  - setuptools==46.4.0
  - six==1.14.0
  - sqlite==3.31.1
  - tensorboard==1.8.0
  - tensorflow==1.8.0
  - termcolor==1.1.0
  - terminado==0.8.3
  - testpath==0.4.4
  - tk==8.6.8
  - tornado==6.0.4
  - traitlets==4.3.3
  - urllib3==1.25.9
  - wcwidth==0.1.9
  - webencodings==0.5.1
  - werkzeug==1.0.1
  - wheel==0.34.2
  - xz==5.2.5
  - zeromq==4.3.2
  - zipp==3.1.0
  - zlib==1.2.11
  - zstd==1.3.7

